<a href="https://colab.research.google.com/github/ijustwanttoputcodehere/Notatniki-Jupyter/blob/main/sgd_alldata.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import SGDClassifier
from sklearn.preprocessing import StandardScaler

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/AMaszynowe/Reuters_exclude_usa.csv')

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/AMaszynowe/ReutersPY.csv')

In [ ]:
df = df.iloc[:,:-1]
df.fillna(0)

labels  standard  oil  Co  ...  decran  gerstner  phelan  dassler
0         usa         3    2   1  ...       0         0       0        0
1         usa         0    0   0  ...       0         0       0        0
2         usa         0    0   0  ...       0         0       0        0
3         usa         0    0   0  ...       0         0       0        0
4         usa         0    1   0  ...       0         0       0        0
...       ...       ...  ...  ..  ...     ...       ...     ...      ...
13436  france         0    0   0  ...       0         0       0        0
13437     usa         0    0   0  ...       0         0       0        0
13438   japan         0    0   1  ...       0         0       0        0
13439     usa         0    0   0  ...       0         0       0        0
13440     usa         0    0   0  ...       0         0       0        0

[13441 rows x 6743 columns]

In [ ]:
df.labels = pd.factorize(df.labels)[0]

X = df.iloc[:,1:].values
y = df['labels'].values

np.unique(y)

array([0, 1, 2, 3, 4, 5])

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

In [ ]:
sgd_clf = SGDClassifier()
sgd_clf.fit(X_train, y_train)

SGDClassifier(alpha=0.0001, average=False, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.0, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='hinge',
              max_iter=1000, n_iter_no_change=5, n_jobs=None, penalty='l2',
              power_t=0.5, random_state=None, shuffle=True, tol=0.001,
              validation_fraction=0.1, verbose=0, warm_start=False)

In [ ]:
y_preds = sgd_clf.predict(X_test)

In [ ]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,y_preds))

[[2612   18   11    1    2    3]
 [  93  119    1    0    0    0]
 [  33    9  190    2    0    2]
 [  10    1    9   40    0    0]
 [  26   14    2    0   69    2]
 [   6    5   10    0    1   70]]


In [ ]:
from sklearn.metrics import precision_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import recall_score

In [ ]:
precision_score(y_test, y_preds,average='weighted')


0.9189373395214336

In [ ]:
accuracy_score(y_test, y_preds)

0.9223445403153824

In [ ]:
recall_score(y_test, y_preds, average='weighted')

0.9223445403153824